export const API_BASE_CANDIDATES = [
  import.meta.env.VITE_API_BASE_URL,
  "https://iith-one.vercel.app",
  "https://iith-udayprakashchamakuri-5279s-projects.vercel.app",
  "https://iith-git-main-udayprakashchamakuri-5279s-projects.vercel.app",
].filter(Boolean);

export const API_BASE = API_BASE_CANDIDATES[0];

export const NAV_ITEMS = [
  { id: "home", label: "Home", icon: "home" },
  { id: "simulation", label: "Discussion", icon: "hub" },
  { id: "intelligence", label: "Overview", icon: "psychology" },
  { id: "automation", label: "Automation", icon: "autorenew" },
  { id: "agents", label: "Team", icon: "groups" },
  { id: "risk", label: "Risks", icon: "shield" },
];

export const AGENT_META = {
  "CEO Agent": {
    initials: "EX1",
    accent: "#ffe16d",
    symbol: "crown",
    label: "CEO",
    title: "Final decision maker",
    boardRole: "Chief Executive Officer",
  },
  "Startup Builder Agent": {
    initials: "BLD",
    accent: "#ff9f59",
    symbol: "rocket_launch",
    label: "Startup Builder",
    title: "Fast execution",
    boardRole: "Startup Builder",
  },
  "Market Research Agent": {
    initials: "RSH",
    accent: "#9ac9ff",
    symbol: "travel_explore",
    label: "Market Research",
    title: "Customer demand research",
    boardRole: "Market Research",
  },
  "Finance Agent": {
    initials: "FIN",
    accent: "#00ff94",
    symbol: "leaderboard",
    label: "Finance",
    title: "Money and budget",
    boardRole: "Finance",
  },
  "Marketing Agent": {
    initials: "MKT",
    accent: "#ddb7ff",
    symbol: "campaign",
    label: "Marketing",
    title: "Messaging and demand",
    boardRole: "Marketing",
  },
  "Pricing Agent": {
    initials: "PRC",
    accent: "#ffdb3c",
    symbol: "sell",
    label: "Pricing",
    title: "Price planning",
    boardRole: "Pricing",
  },
  "Supply Chain Agent": {
    initials: "OPS",
    accent: "#7be7d4",
    symbol: "local_shipping",
    label: "Operations",
    title: "Delivery and operations",
    boardRole: "Supply Chain",
  },
  "Hiring Agent": {
    initials: "HIR",
    accent: "#f7a6c6",
    symbol: "groups",
    label: "Hiring",
    title: "Team planning",
    boardRole: "Hiring",
  },
  "Risk Agent": {
    initials: "RSK",
    accent: "#ff8f8f",
    symbol: "security",
    label: "Risk",
    title: "What could go wrong",
    boardRole: "Risk",
  },
  "Sales Strategy Agent": {
    initials: "SLS",
    accent: "#ffb870",
    symbol: "handshake",
    label: "Sales",
    title: "Sales plan",
    boardRole: "Sales Strategy",
  },
};

export const DEMO_CASES = [
  {
    id: "hyderabad-creator-arena",
    label: "Hyderabad gaming and creator arena",
    summary: "A high-stakes launch case: can a late-night gaming arena and creator studio near Gachibowli become a real business before rent, fit-out, and repeat-demand risk kill it?",
    form: {
      company_name: "NightShift Arena",
      industry: "Entertainment and creator economy",
      region: "India",
      company_stage: "Idea",
      business_problem:
        "We want to open a late-night gaming arena and creator studio near Gachibowli in Hyderabad. The business would make money from hourly PC and console gaming, memberships, small esports tournaments, a snack counter, and rentable streaming booths for creators. The area has strong student and young-professional traffic, but the fit-out cost is heavy, rent is expensive, power backup matters, and repeat demand is still unproven. We have about 10 months of cash to work with, expect gross margin around 58% once the venue is stable, and think it may take 9 months to win back customer acquisition and launch spend. The team needs to decide whether to launch now, move forward with changes, or wait.",
      objectives:
        "Reach break-even quickly, build strong repeat traffic, create a standout local destination, and avoid a heavy fixed-cost mistake",
      current_constraints:
        "High rent, expensive fit-out, uncertain weekday demand, price-sensitive audience, and a small starting team",
      extra_context:
        "The strongest early demand is likely to come from college students, esports communities, and young software employees who want a premium social gaming venue, not just another cafe.",
      runway_months: "10",
      gross_margin: "58",
      cac_payback_months: "9",
      price_point: "349",
      variation_name: "Weak weekday traffic case",
      variation_budget_change_pct: "-18",
      variation_market_condition: "bearish",
      variation_competition_level: "high",
      variation_pricing_change_pct: "-8",
      variation_notes: "Assume weekday demand is weaker than planned, students resist premium pricing, and the venue fills mainly on weekends.",
    },
  },
  {
    id: "college-game-center",
    label: "Game center near a college",
    summary: "A local entertainment business deciding whether to open near a campus and how to price memberships.",
    form: {
      company_name: "Campus Arena",
      industry: "Entertainment",
      region: "India",
      company_stage: "Idea",
      business_problem:
        "I want to start a game center near a college. The plan is to offer PC gaming, console gaming, small tournaments, and snacks. The area has strong student traffic, but students are price-sensitive and the business would need a decent upfront fit-out, gaming equipment, rent, and staff. I need to know whether this can work, how risky it is, and what kind of pricing and launch plan would make sense.",
      objectives: "Reach break-even fast, attract repeat visits, build a student community",
      current_constraints: "Limited startup capital, uncertain weekday demand, high upfront equipment cost",
      extra_context:
        "The location is close to hostels and coaching centers, and I may also host weekend esports events.",
      runway_months: "10",
      gross_margin: "55",
      cac_payback_months: "6",
      price_point: "299",
      variation_name: "Low-demand semester break case",
      variation_budget_change_pct: "-15",
      variation_market_condition: "bearish",
      variation_competition_level: "medium",
      variation_pricing_change_pct: "-5",
      variation_notes: "Assume foot traffic drops during exam season and semester breaks.",
    },
  },
  {
    id: "d2c-skincare",
    label: "Online skincare brand",
    summary: "A direct-to-consumer brand testing whether it should scale ads and add new products.",
    form: {
      company_name: "PureGlow Labs",
      industry: "Consumer goods",
      region: "Asia-Pacific",
      company_stage: "Pre-seed",
      business_problem:
        "We sell a small set of skincare products online and are considering whether to increase ad spend and launch two new products before the festive season. Sales have been growing, but return rates, ad costs, and repeat purchase rates are still uneven. We need to decide whether to scale now or tighten the business first.",
      objectives: "Grow monthly sales, improve repeat purchases, launch before the festive season",
      current_constraints: "Rising ad costs, limited inventory budget, uncertain repeat rate",
      extra_context: "Most sales come from Instagram and our own website, and our best-selling product is a vitamin C serum.",
      runway_months: "9",
      gross_margin: "62",
      cac_payback_months: "8",
      price_point: "1499",
      variation_name: "Ad costs spike case",
      variation_budget_change_pct: "-10",
      variation_market_condition: "base",
      variation_competition_level: "high",
      variation_pricing_change_pct: "0",
      variation_notes: "Assume paid social costs rise sharply for the next 90 days.",
    },
  },
  {
    id: "ev-charging-app",
    label: "EV charging app partnership",
    summary: "A mobility startup considering a city expansion through charger-network partnerships.",
    form: {
      company_name: "VoltPath",
      industry: "Mobility technology",
      region: "Europe",
      company_stage: "Series A",
      business_problem:
        "We have an app that helps electric vehicle drivers find and book charging slots. We are considering entering two more cities through partnerships with charging-station operators. The upside is faster growth, but integration work, partner dependence, and customer support complexity could all increase. We need a decision on whether to expand now.",
      objectives: "Expand city coverage, grow active users, build strong partner relationships",
      current_constraints: "Integration complexity, partner dependency, limited operations bandwidth",
      extra_context: "Our current cities perform well on weekends but weekday bookings are still inconsistent.",
      runway_months: "14",
      gross_margin: "58",
      cac_payback_months: "11",
      price_point: "120",
      variation_name: "Partner delay case",
      variation_budget_change_pct: "-5",
      variation_market_condition: "base",
      variation_competition_level: "medium",
      variation_pricing_change_pct: "3",
      variation_notes: "Assume one large charging partner delays integration by two months.",
    },
  },
  {
    id: "test-prep-center",
    label: "Test prep and tutoring center",
    summary: "An education business deciding whether to open a physical center and offer hybrid classes.",
    form: {
      company_name: "ScoreBridge",
      industry: "Education",
      region: "India",
      company_stage: "Established business",
      business_problem:
        "We run a small online test-prep business and are thinking about opening a physical tutoring center near a dense student neighborhood. The center could improve trust and retention, but rent, faculty hiring, and operations would become much heavier. We need to decide whether a physical center makes sense now and what a safe first step would look like.",
      objectives: "Increase enrollment, improve retention, build local brand trust",
      current_constraints: "Faculty hiring risk, rent commitments, uneven enrollment by month",
      extra_context: "Students mainly come for engineering and government exam preparation, and parents care a lot about reputation and results.",
      runway_months: "13",
      gross_margin: "48",
      cac_payback_months: "5",
      price_point: "18000",
      variation_name: "Slow enrollment case",
      variation_budget_change_pct: "-20",
      variation_market_condition: "base",
      variation_competition_level: "high",
      variation_pricing_change_pct: "-8",
      variation_notes: "Assume enrollment fills slower than expected in the first two months.",
    },
  },
  {
    id: "cloud-kitchen",
    label: "Cloud kitchen expansion",
    summary: "A food business deciding whether to open a second kitchen and add aggregator-heavy growth.",
    form: {
      company_name: "Urban Tiffin Co.",
      industry: "Food service",
      region: "Middle East & Africa",
      company_stage: "Established business",
      business_problem:
        "Our cloud kitchen has built a loyal local customer base, and we are considering opening a second kitchen to cover another delivery zone. The new kitchen could increase revenue, but food-delivery commissions, staffing, and quality control are already under pressure. We need to decide whether expansion now is smart or too risky.",
      objectives: "Grow order volume, keep food quality high, maintain profit",
      current_constraints: "Delivery app commissions, staffing gaps, quality consistency across locations",
      extra_context: "Dinner orders are strong, but lunch demand is still inconsistent and customer ratings drop when delivery times slip.",
      runway_months: "8",
      gross_margin: "44",
      cac_payback_months: "4",
      price_point: "12",
      variation_name: "Commission pressure case",
      variation_budget_change_pct: "-12",
      variation_market_condition: "base",
      variation_competition_level: "high",
      variation_pricing_change_pct: "5",
      variation_notes: "Assume delivery platforms raise commission and customer discounts become harder to sustain.",
    },
  },
];

export const sampleProblem = DEMO_CASES[0].form.business_problem;

export const defaultTimeline = [
  { round: 1, synopsis: "Round 1 - each advisor shares an opening view." },
  { round: 2, synopsis: "Round 2 - the team challenges weak assumptions." },
  { round: 3, synopsis: "Round 3 - the team agrees on next steps." },
];
